# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: www.timbeghin.com  
title: Tim Beghin
email: your-email@domain.com
author: Tim Beghin
description: > # "Write an awesome description for your new site here. 
  Personal Website for Tim Beghin, Engineer. Renewables, Data & People
copyright: 'Copyright &copy; 2018 Tim Beghin. All Rights Reserved.'
credits: Made with ❤ in RSA

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/timbeghin
  - title: linkedin
    url: https://www.linkedin.com/in/timothybeghin/
